### ISSUE TITLE
Error message on failure

### ISSUE THREAD

**Issue by kelunik** [pierky/sct-verify#2]
If no SCTs are present via the TLS extension, there should be a nice error message instead of a trace.

```
$ ./sct-verify.py www.chase.com
Traceback (most recent call last):
  File "./sct-verify.py", line 262, in <module>
    Offset, TLS_ExtensionType, TLS_ExtensionLen = Read( Data, Offset, "!HH" )
  File "./sct-verify.py", line 151, in Read
    Values = struct.unpack_from( format, buf, offset )
struct.error: unpack_from requires a buffer of at least 4 bytes
```

**Comment by pierky** [comment]
Thanks for reporting it.

```
$ ./sct-verify.py www.chase.com
Not TLS extensions found.
```
